# Generated by Django 5.2 on 2025-04-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_guestsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestsession',
            name='data',
        ),
        migrations.AddField(
            model_name='guestsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
