# Generated by Django 5.2 on 2025-04-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_guestsession_data_guestsession_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestsession',
            name='is_active',
        ),
    ]
